/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hcmus.client.gui;

import hcmus.client.entity.ShareFile;
import hcmus.client.service.Manager;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.CharacterIterator;
import java.text.StringCharacterIterator;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DevClientForm extends javax.swing.JFrame {

    /**
     * Creates new form DevClientForm
     */
    CardLayout mainCardLayout;
    Color defaultColor = new Color(204, 204, 204);
    static final String[] ServerColums = new String[]{"STT", "IP", "PORT", "Số lượng File"};
    static final String[] FileColums = new String[]{"STT", "Tên file", "Kích thước file", "Chọn",};
    static final String[] FileStatusColums = new String[]{"File name", "File server", "Port", "Download",};
    String listServer;// = "192.168.1.1`3306`file1.txt\t200:file2.txt\t1000>192.168.3.3`5578`filetest1.txt\t1024:filetest2.txt\t500:filestudent.csv\t300";
    private List<String> currentInfoServer = null;
    private List<ShareFile> listChoosen;

    public DevClientForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        mainCardLayout = (CardLayout) (pnMainCard.getLayout());
        mainCardLayout.show(pnMainCard, "pnListServer");
        btnListServer.setBackground(Color.white);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        JTListServer.setDefaultRenderer(Object.class, centerRenderer);
        JTListFile.setDefaultRenderer(Object.class, centerRenderer);
        JTListStatusFile.setDefaultRenderer(Object.class, centerRenderer);
        getAllFileServer();

    }

    private void getAllFileServer() {
        listServer = Manager.getInstance().getFileServer();
        loadListServer();
    }

    private void loadListServer() {
        DefaultTableModel model = new DefaultTableModel(null, ServerColums) {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };

        String[] servers = listServer.split(">");
        for (int i = 0; i < servers.length; i++) {
            String[] info = servers[i].split("`");
            String[] files = info[2].split(":");
            Object[] items = new Object[]{i + 1, info[0], info[1], files.length};
            model.addRow(items);
        }
        JTListServer.setModel(model);
        JTListServer.setRowSelectionInterval(0, 0);
    }

    public static String humanReadableByteCountSI(long bytes) {
        if (-1000 < bytes && bytes < 1000) {
            return bytes + " B";
        }
        CharacterIterator ci = new StringCharacterIterator("KMGTPE");
        while (bytes <= -999_950 || bytes >= 999_950) {
            bytes /= 1000;
            ci.next();
        }
        return String.format("%.1f %cB", bytes / 1000.0, ci.current());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelSidebar = new javax.swing.JPanel();
        btnStatus = new javax.swing.JButton();
        btnListServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        pnMainCard = new javax.swing.JPanel();
        pnStatusFile = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTListStatusFile = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnListServer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTListServer = new javax.swing.JTable();
        btnConnect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        pnListFile = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbIP = new javax.swing.JLabel();
        lbPort = new javax.swing.JLabel();
        lbNumofFile = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTListFile = new javax.swing.JTable();
        btnDownLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(1);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(200, 102));

        panelSidebar.setBackground(new java.awt.Color(102, 153, 255));

        btnStatus.setBackground(new java.awt.Color(204, 204, 204));
        btnStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnStatus.setText("Trạng thái tải file");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });

        btnListServer.setBackground(new java.awt.Color(204, 204, 204));
        btnListServer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnListServer.setText("Danh sách server");
        btnListServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListServerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NTK team");

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(btnListServer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelSidebar);

        pnMainCard.setPreferredSize(new java.awt.Dimension(625, 300));
        pnMainCard.setLayout(new java.awt.CardLayout());

        JTListStatusFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTListStatusFile.setRowSelectionAllowed(false);
        JTListStatusFile.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(JTListStatusFile);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Danh sách lịch sử các file tải xuống");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Danh sách File:");

        javax.swing.GroupLayout pnStatusFileLayout = new javax.swing.GroupLayout(pnStatusFile);
        pnStatusFile.setLayout(pnStatusFileLayout);
        pnStatusFileLayout.setHorizontalGroup(
            pnStatusFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStatusFileLayout.createSequentialGroup()
                .addGroup(pnStatusFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnStatusFileLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel6))
                    .addGroup(pnStatusFileLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnStatusFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnStatusFileLayout.setVerticalGroup(
            pnStatusFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnStatusFileLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMainCard.add(pnStatusFile, "pnStatusFile");

        JTListServer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTListServer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(JTListServer);

        btnConnect.setBackground(new java.awt.Color(204, 204, 204));
        btnConnect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Danh sách server:");

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnListServerLayout = new javax.swing.GroupLayout(pnListServer);
        pnListServer.setLayout(pnListServerLayout);
        pnListServerLayout.setHorizontalGroup(
            pnListServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListServerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnListServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnListServerLayout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnListServerLayout.createSequentialGroup()
                        .addGroup(pnListServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnListServerLayout.setVerticalGroup(
            pnListServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListServerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnListServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pnMainCard.add(pnListServer, "pnListServer");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin server", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbIP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIP.setText("IP:");

        lbPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPort.setText("Port:");

        lbNumofFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNumofFile.setText("Số lượng File:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbNumofFile)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPort)
                            .addComponent(lbIP))
                        .addGap(62, 130, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNumofFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Danh sách File:");

        JTListFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTListFile.setRowSelectionAllowed(false);
        JTListFile.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(JTListFile);

        btnDownLoad.setBackground(new java.awt.Color(204, 204, 204));
        btnDownLoad.setText("Tải xuống");
        btnDownLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnListFileLayout = new javax.swing.GroupLayout(pnListFile);
        pnListFile.setLayout(pnListFileLayout);
        pnListFileLayout.setHorizontalGroup(
            pnListFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListFileLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnListFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnListFileLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListFileLayout.createSequentialGroup()
                        .addGroup(pnListFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                            .addGroup(pnListFileLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDownLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(pnListFileLayout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
        );
        pnListFileLayout.setVerticalGroup(
            pnListFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListFileLayout.createSequentialGroup()
                .addGroup(pnListFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnListFileLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListFileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDownLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMainCard.add(pnListFile, "pnListFile");

        jSplitPane1.setRightComponent(pnMainCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed

        mainCardLayout.show(pnMainCard, "pnStatusFile");
        btnStatus.setBackground(Color.white);
        btnListServer.setBackground(defaultColor);

        DefaultTableModel model = new DefaultTableModel(null, FileStatusColums) {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
        //Data demo
        String listFileServer = "fileTest1.txt`192.168.1.1`8805`75%>fileTest2.txt`127.0.0.3`8879`33%>student.csv`192.168.1.45`3306`100%";
        String[] infoFileServers = listFileServer.split(">");
        for (int i = 0; i < infoFileServers.length; i++) {
            String[] detailInfo = infoFileServers[i].split("`");
            Object[] items = new Object[]{detailInfo[0], detailInfo[1], detailInfo[2], detailInfo[3]};
            model.addRow(items);
        }
        JTListStatusFile.setModel(model);
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnListServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListServerActionPerformed

        mainCardLayout.show(pnMainCard, "pnListServer");
        btnListServer.setBackground(Color.white);
        btnStatus.setBackground(defaultColor);
    }//GEN-LAST:event_btnListServerActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(0);

    }//GEN-LAST:event_btnExitActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        mainCardLayout.show(pnMainCard, "pnListFile");
        String[] servers = listServer.split(">");
        String[] info = servers[JTListServer.getSelectedRow()].split("`");
        lbIP.setText("IP: " + info[0]);
        lbPort.setText("Port: " + info[1]);
        String[] listFile = info[info.length - 1].split(":");
        lbNumofFile.setText("Số lượng File: " + listFile.length);
        DefaultTableModel model = new DefaultTableModel(null, FileColums) {
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return String.class;
                    case 1:
                        return String.class;
                    case 2:
                        return String.class;
                    case 3:
                        return Boolean.class;
                    default:
                        return String.class;
                }
            }

            @Override
            public boolean isCellEditable(int i, int i1) {
                if (i1 == 3) {
                    return true;
                }
                return false;
            }
        };

        listChoosen = new ArrayList();

        for (int i = 0; i < listFile.length; i++) {
            String[] result = listFile[i].split("\t");
            String fileSize = humanReadableByteCountSI(Long.parseLong(result[1]));
            Object[] items = new Object[]{i + 1, result[0], fileSize, false};
            model.addRow(items);

            listChoosen.add(new ShareFile(
                    result[0],
                    Long.valueOf(result[1])
            ));
        }
        JTListFile.setModel(model);

    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainCardLayout.show(pnMainCard, "pnListServer");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDownLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownLoadActionPerformed
        // TODO add your handling code here:
        List<ShareFile> choosenFile = new ArrayList();

        int count = 0;
        for (int i = 0; i < JTListFile.getRowCount(); i++) {
            Boolean checked = Boolean.valueOf(JTListFile.getValueAt(i, 3).toString());
            if (checked) {
                choosenFile.add(listChoosen.get(i));
                count++;
            }
        }
        if (count == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn file để download!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        //Danh sách các file được chon
        System.out.println("Danh sách các file được chọn");
        for (int i = 0; i < choosenFile.size(); i++) {
            System.out.println(choosenFile.get(i).getFileName());
            System.out.println(choosenFile.get(i).getFileSize());

        }
    }//GEN-LAST:event_btnDownLoadActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        getAllFileServer();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTListFile;
    private javax.swing.JTable JTListServer;
    private javax.swing.JTable JTListStatusFile;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDownLoad;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnListServer;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbIP;
    private javax.swing.JLabel lbNumofFile;
    private javax.swing.JLabel lbPort;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel pnListFile;
    private javax.swing.JPanel pnListServer;
    private javax.swing.JPanel pnMainCard;
    private javax.swing.JPanel pnStatusFile;
    // End of variables declaration//GEN-END:variables
}
